service: product-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getAllProducts:
    handler: handler_products.getAllProducts
    events:
      - http:
          path: products
          method: get
          cord: true

  getProductById:
    handler: handler_by_id.getProductById
    events:
      - http:
          path: product/{productId}
          method: get
          cord: true
          request:
            parameters:
              paths:
                productId: true
