service: import-service
frameworkVersion: '2'
variablesResolutionMode: 20210219


provider:
  name: aws
    runtime: nodejs14.x
    stage: dev
    region: eu-west-1
    lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::node-in-aws-cloud-catalogs"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::node-in-aws-cloud-catalogs/*"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: handler.importFileParser
               - s3:
               bucket: uploaded
               event: s3:ObjectCreated:*
               existing: true
